"""Add Leaderboard and Scores tables

Revision ID: fde4d52c4093
Revises: 1a31ce608336
Create Date: 2025-09-28 23:26:28.870836

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'fde4d52c4093'
down_revision = '1a31ce608336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leaderboard',
    sa.Column('event_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_table('scores',
    sa.Column('duration', sa.Interval(), nullable=False),
    sa.Column('challenge_score', sa.Integer(), nullable=False),
    sa.Column('cg_score', sa.Integer(), nullable=False),
    sa.Column('si_score', sa.Integer(), nullable=False),
    sa.Column('mr_score', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['leaderboard.event_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scores')
    op.drop_table('leaderboard')
    # ### end Alembic commands ###
