/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecruiterDashboardRouteImport } from './routes/recruiter-dashboard'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as PostGameLeaderboardRouteImport } from './routes/post-game-leaderboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HomepageRouteImport } from './routes/homepage'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as RecordIndexRouteImport } from './routes/record/index'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutGameRouteImport } from './routes/_layout/game'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecruiterDashboardRoute = RecruiterDashboardRouteImport.update({
  id: '/recruiter-dashboard',
  path: '/recruiter-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PostGameLeaderboardRoute = PostGameLeaderboardRouteImport.update({
  id: '/post-game-leaderboard',
  path: '/post-game-leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomepageRoute = HomepageRouteImport.update({
  id: '/homepage',
  path: '/homepage',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordIndexRoute = RecordIndexRouteImport.update({
  id: '/record/',
  path: '/record/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutGameRoute = LayoutGameRouteImport.update({
  id: '/game',
  path: '/game',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/homepage': typeof HomepageRoute
  '/login': typeof LoginRoute
  '/post-game-leaderboard': typeof PostGameLeaderboardRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/recruiter-dashboard': typeof RecruiterDashboardRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/game': typeof LayoutGameRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/record': typeof RecordIndexRoute
}
export interface FileRoutesByTo {
  '/homepage': typeof HomepageRoute
  '/login': typeof LoginRoute
  '/post-game-leaderboard': typeof PostGameLeaderboardRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/recruiter-dashboard': typeof RecruiterDashboardRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/game': typeof LayoutGameRoute
  '/items': typeof LayoutItemsRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
  '/record': typeof RecordIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/homepage': typeof HomepageRoute
  '/login': typeof LoginRoute
  '/post-game-leaderboard': typeof PostGameLeaderboardRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/recruiter-dashboard': typeof RecruiterDashboardRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/game': typeof LayoutGameRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
  '/record/': typeof RecordIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/homepage'
    | '/login'
    | '/post-game-leaderboard'
    | '/recover-password'
    | '/recruiter-dashboard'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/game'
    | '/items'
    | '/settings'
    | '/'
    | '/record'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/homepage'
    | '/login'
    | '/post-game-leaderboard'
    | '/recover-password'
    | '/recruiter-dashboard'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/game'
    | '/items'
    | '/settings'
    | '/'
    | '/record'
  id:
    | '__root__'
    | '/_layout'
    | '/homepage'
    | '/login'
    | '/post-game-leaderboard'
    | '/recover-password'
    | '/recruiter-dashboard'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/game'
    | '/_layout/items'
    | '/_layout/settings'
    | '/_layout/'
    | '/record/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  HomepageRoute: typeof HomepageRoute
  LoginRoute: typeof LoginRoute
  PostGameLeaderboardRoute: typeof PostGameLeaderboardRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  RecruiterDashboardRoute: typeof RecruiterDashboardRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  RecordIndexRoute: typeof RecordIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recruiter-dashboard': {
      id: '/recruiter-dashboard'
      path: '/recruiter-dashboard'
      fullPath: '/recruiter-dashboard'
      preLoaderRoute: typeof RecruiterDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/post-game-leaderboard': {
      id: '/post-game-leaderboard'
      path: '/post-game-leaderboard'
      fullPath: '/post-game-leaderboard'
      preLoaderRoute: typeof PostGameLeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homepage': {
      id: '/homepage'
      path: '/homepage'
      fullPath: '/homepage'
      preLoaderRoute: typeof HomepageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/record/': {
      id: '/record/'
      path: '/record'
      fullPath: '/record'
      preLoaderRoute: typeof RecordIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/game': {
      id: '/_layout/game'
      path: '/game'
      fullPath: '/game'
      preLoaderRoute: typeof LayoutGameRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutGameRoute: typeof LayoutGameRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutGameRoute: LayoutGameRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  HomepageRoute: HomepageRoute,
  LoginRoute: LoginRoute,
  PostGameLeaderboardRoute: PostGameLeaderboardRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  RecruiterDashboardRoute: RecruiterDashboardRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  RecordIndexRoute: RecordIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
